
print('     _ _ _ ___ _ _      ')
time.sleep()
print('    / _   /    |  _  \     ')
time.sleep(3)
print('   |/   /  / _  | |)  |    ')
time.sleep(3)
print('       /  / /_\ |  __/     ')
time.sleep(3)
print('      /  /       | |         ')
time.sleep(3)
print('     /  / _/ \_| |         ')
time.sleep(3)
print('                         ')
print('\n')
time.sleep(5)
print('===============================')
time.sleep(3)
print('=          doni projek        =')
time.sleep(3)
print('===============================')
time.sleep(3)
print('AUTHOR : Jihan Maulana')
print('\n')
